version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: jsjsjs
      POSTGRES_PASSWORD: jsjsjs
    ports:
      - "5432:5432"
    volumes:
      - .\\postgres_data:/var/lib/postgresql/data